version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    environment:
      - SS_ORG_ID=eff186f8-253f-40eb-8187-4f15bbd1adcd
      - SS_CLIENT=rDYstNWgbLQ8ZFXU52HuGnUwrdJe89tdyulfqmz3SDXGNJA9
      - SS_SECRET=BMKgJ87MOPfdPxFAnBl5fp1p4sy9pcPNQ4gdtRjftnX97tUbo6a1CItWMIPSvqng
      - SS_MODE=sandbox
      - SS_API_URL=https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1
      - SS_STAGING=https://api-satusehat-stg.dto.kemkes.go.id/fhir-r4/v1
    depends_on:
      - oracle-db
    networks:
      - app-network

  oracle-db:
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=root
      - ORACLE_ENABLE_XDB=true
    ports:
      - "1521:1521"
      - "5500:5500"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
